# Generated by Django 4.0.6 on 2022-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_dym_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('feature', models.TextField(verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Наклонно-сдвижная система',
                'verbose_name_plural': 'Наклонно-сдвижные системы',
            },
        ),
    ]
