# Generated by Django 4.0.6 on 2022-08-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('feature', models.TextField(verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Остекление фасада',
                'verbose_name_plural': 'Остекление фасадов',
            },
        ),
    ]
